spring:
  application:
    name: linkhub
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    #para ver las consultas en consola
    logging:
      level:
        org.springframework.data.r2dbc: DEBUG
        org.springframework.security: DEBUG